
from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class SessionNotFound(ResourceNotFound):
    """Raised when the session is not found in DataLab"""
    def __init__(self, session_id: str, correlation_id: str = None):
        super().__init__(f"The requested session id {session_id} was not found", correlation_id)

class UrlParsingFailed(Exception):
    """Raised when the session id cannot be parsed from the URL query"""
    def __init__(self, url_query: str):
        super().__init__(f"The session id could not be found in the URL query {url_query}.")

class SnapshotRegistrationFailed(Exception):
    """Raised when the outputs failed to be registered as a snapshot."""
    def __init__(self, session_id: str):
        super().__init__(f"The snapshot registration failed for session id {session_id}.")
